name = "PyFormattedStrings"
uuid = "5f89f4a4-a228-4886-b223-c468a82ed5b9"
authors = ["Alexander Plavin <alexander@plav.in>"]
version = "0.1.9"

[deps]
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
IterTools = "1.3"
julia = "1.5"
