name = "PyFormattedStrings"
uuid = "5f89f4a4-a228-4886-b223-c468a82ed5b9"
authors = ["Alexander Plavin <alexander@plav.in>"]
version = "0.1.11"

[deps]
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SnoopPrecompile = "66db9d55-30c0-4569-8b51-7e840670fc0c"

[compat]
Printf = "1"
SnoopPrecompile = "1.0.3"
julia = "1.5"
